"""init project

Revision ID: e506f53a991b
Revises:
Create Date: 2024-05-18 19:48:14.030039

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e506f53a991b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "query_history",
            sa.String(length=512),
            nullable=True,
            comment="query_history",
        ),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Chat history table",
    )
    op.create_index(op.f("ix_chat_history_id"), "chat_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_history_id"), table_name="chat_history")
    op.drop_table("chat_history")
    # ### end Alembic commands ###
